server:
  port: 7801

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mock?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: mobike001
    password: m0bike123
    hikari:
      maxLifetime: 3600000
      maximumPoolSize: 50
      connectionTestQuery: select 1;

mybatis:
  mapper-locations: classpath:mapper/*.xml